package DAOs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import Utils.DatabaseConnectionManager;
import org.json.JSONObject;

public class ReportDAO {

    private Connection getConnection() throws SQLException {
        return DatabaseConnectionManager.getNode3TransactionsConnection();
    }

    /**
     * Inserts a generated report into the reports table.
     * @return the generated report_id, or -1 on failure
     */
    public int insertReport(int generatedBy, String type, String parameters, String content) {
        String sql = "INSERT INTO reports (generated_by, type, parameters, content) VALUES (?, ?, ?, ?) RETURNING report_id";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, generatedBy);
            pstmt.setString(2, type);
            pstmt.setObject(3, parameters, Types.OTHER);
            pstmt.setString(4, content);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    int reportId = rs.getInt("report_id");
                    System.out.println("[ReportDAO] Report saved to DB — id=" + reportId + ", type=" + type + ", generatedBy=" + generatedBy);
                    return reportId;
                }
            }
        } catch (SQLException e) {
            System.err.println("[ReportDAO] Failed to insert report — type=" + type + ", generatedBy=" + generatedBy);
            e.printStackTrace();
        }
        return -1;
    }

    /**
     * Retrieves all reports generated by a specific user, ordered by newest first.
     */
    public List<JSONObject> getReportsByUserId(int userId) {
        List<JSONObject> reports = new ArrayList<>();
        String sql = "SELECT report_id, generated_by, type, parameters, content, generated_at FROM reports WHERE generated_by = ? ORDER BY generated_at DESC";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, userId);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    JSONObject report = new JSONObject();
                    report.put("reportId", rs.getInt("report_id"));
                    report.put("generatedBy", rs.getInt("generated_by"));
                    report.put("type", rs.getString("type"));
                    String params = rs.getString("parameters");
                    report.put("parameters", params != null ? params : "{}");
                    report.put("content", rs.getString("content"));
                    report.put("generatedAt", rs.getString("generated_at"));
                    reports.add(report);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return reports;
    }

    /**
     * Retrieves all reports, ordered by newest first (admin use).
     */
    public List<JSONObject> getAllReports() {
        List<JSONObject> reports = new ArrayList<>();
        String sql = "SELECT report_id, generated_by, type, parameters, content, generated_at FROM reports ORDER BY generated_at DESC";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                JSONObject report = new JSONObject();
                report.put("reportId", rs.getInt("report_id"));
                report.put("generatedBy", rs.getInt("generated_by"));
                report.put("type", rs.getString("type"));
                String params = rs.getString("parameters");
                report.put("parameters", params != null ? params : "{}");
                report.put("content", rs.getString("content"));
                report.put("generatedAt", rs.getString("generated_at"));
                reports.add(report);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return reports;
    }
}
